# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
  profile: adam
functions:
  workoutapp:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: server.graphqlHandler
    environment: 
      MODE: whatever
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
